import bcrypt from "bcryptjs";
const data = {
  imgURL: "https://amazona.webacademy.pro/images/",
  users: [
    {
      name: "Admin",
      email: "admin@gmail.com",
      password: bcrypt.hashSync("1234", 8),
      isAdmin: true,
    },
    {
      name: "Sunny",
      email: "user@gmail.com",
      password: bcrypt.hashSync("1234", 8),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: "Nike Slim Shirt",
      category: "Shirts",
      image: "p1.jpg",
      price: 120,
      countInStock: 10,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      name: "Puma Slim Shirt",
      category: "Shirts",
      image: "p2.jpg",
      price: 140,
      countInStock: 20,
      brand: "Puma",
      rating: 4,
      numReviews: 11,
      description: "high quality product",
    },
    {
      name: "Adidas Slim Shirt",
      category: "Shirts",
      image: "p3.jpg",
      price: 120,
      countInStock: 0,
      brand: "Adidas",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      name: "Nike Pant",
      category: "pants",
      image: "p4.jpg",
      price: 80,
      countInStock: 50,
      brand: "Nike",
      rating: 3.5,
      numReviews: 12,
      description: "high quality product",
    },
    {
      name: "Puma Pant",
      category: "pants",
      image: "p5.jpg",
      price: 70,
      countInStock: 10,
      brand: "Puma",
      rating: 2.5,
      numReviews: 16,
      description: "high quality product",
    },
    {
      name: "Adidas Pant",
      category: "pants",
      image: "p6.jpg",
      price: 64,
      countInStock: 30,
      brand: "Adidas",
      rating: 4.5,
      numReviews: 20,
      description: "high quality product",
    },
  ],
};

export default data;
